#!/usr/bin/env php
<?php
// set to run indefinitely if needed
set_time_limit(0);

// include the composer autoloader
require_once __DIR__ . '/vendor/autoload.php';

// Config Setup
$configPaths = array(
    __DIR__.'/config/commands.php',
    __DIR__.'/config/global.php',
    __DIR__.'/config/local.php',
    __DIR__.'/etc/deploy',
);

$bootstrap = new \Reliv\Deploy\Bootstrap($configPaths);
$bootstrap->run();